/**
 * Global hardcoded course list for Jordanian universities.
 * Used as a FALLBACK when the Supabase database courses are empty or limited.
 * Covers common courses at PSUT, UJ, GJU, JUST, AAU, and other Jordanian universities.
 */

export const COURSE_CATEGORIES: Record<string, string[]> = {
  "Mathematics": [
    "Calculus 1",
    "Calculus 2",
    "Calculus 3",
    "Linear Algebra",
    "Discrete Mathematics",
    "Differential Equations",
    "Numerical Analysis",
    "Statistics",
    "Probability & Statistics",
    "Engineering Mathematics",
    "Business Mathematics",
    "Mathematical Analysis",
    "Abstract Algebra",
    "Number Theory",
    "Complex Analysis",
    "Real Analysis",
    "Topology",
    "Operations Research",
    "Graph Theory",
    "Mathematical Logic",
    "Partial Differential Equations",
    "Combinatorics",
    "Optimization",
    "Stochastic Processes",
    "Mathematical Modeling",
  ],

  "Computer Science": [
    "Introduction to Programming",
    "Structured Programming",
    "Object-Oriented Programming",
    "Data Structures",
    "Algorithms",
    "Database Systems",
    "Operating Systems",
    "Computer Networks",
    "Software Engineering",
    "Web Development",
    "Mobile App Development",
    "Artificial Intelligence",
    "Machine Learning",
    "Computer Architecture",
    "Compiler Design",
    "Theory of Computation",
    "Cybersecurity",
    "Cloud Computing",
    "Computer Graphics",
    "Human-Computer Interaction",
    "Distributed Systems",
    "Digital Logic Design",
    "Assembly Language",
    "Python Programming",
    "Java Programming",
    "C++ Programming",
    "Data Mining",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Information Retrieval",
    "Software Testing",
    "Software Project Management",
    "Requirements Engineering",
    "Parallel Computing",
    "Internet of Things",
    "Blockchain Technology",
    "Big Data Analytics",
    "Information Security",
    "Network Security",
    "Embedded Systems",
    "Game Development",
    "DevOps",
    "API Design",
    "UI/UX Design",
    "Linux Administration",
    "System Programming",
    "Formal Methods",
  ],

  "Engineering": [
    "Statics",
    "Dynamics",
    "Thermodynamics",
    "Fluid Mechanics",
    "Mechanics of Materials",
    "Engineering Drawing",
    "CAD/CAM",
    "Circuit Analysis",
    "Electronics",
    "Digital Electronics",
    "Signals & Systems",
    "Control Systems",
    "Power Systems",
    "Electromagnetics",
    "Communication Systems",
    "Microprocessors",
    "Engineering Economy",
    "Project Management",
    "Environmental Engineering",
    "Structural Analysis",
    "Concrete Design",
    "Steel Design",
    "Surveying",
    "Transportation Engineering",
    "Geotechnical Engineering",
    "Water Resources Engineering",
    "Construction Management",
    "Materials Science",
    "Heat Transfer",
    "Machine Design",
    "Manufacturing Processes",
    "Industrial Engineering",
    "Quality Control",
    "Robotics",
    "Mechatronics",
    "Renewable Energy Systems",
    "Power Electronics",
    "Electric Machines",
    "Instrumentation",
    "Process Control",
    "Chemical Engineering Principles",
    "Reaction Engineering",
    "Mass Transfer",
    "Petroleum Engineering",
    "Mining Engineering",
    "Highway Engineering",
    "Foundation Engineering",
    "Earthquake Engineering",
    "Hydraulics",
    "Irrigation Engineering",
    "Engineering Ethics",
    "Engineering Statistics",
    "Technical Report Writing",
    "Senior Design Project",
    "Engineering Training",
    "Wireless Communications",
    "Digital Signal Processing",
    "VLSI Design",
    "Antenna Design",
    "Biomedical Engineering",
    "Medical Imaging",
  ],

  "Physics": [
    "Physics 1",
    "Physics 2",
    "Physics 3",
    "Modern Physics",
    "Quantum Mechanics",
    "Classical Mechanics",
    "Optics",
    "Electricity & Magnetism",
    "Waves & Oscillations",
    "Nuclear Physics",
    "Solid State Physics",
    "Physics Lab 1",
    "Physics Lab 2",
    "Astrophysics",
    "Thermal Physics",
    "Statistical Mechanics",
    "Particle Physics",
    "Plasma Physics",
    "Mathematical Physics",
    "Computational Physics",
    "Electronics for Physicists",
    "Laser Physics",
    "Spectroscopy",
  ],

  "Chemistry": [
    "General Chemistry 1",
    "General Chemistry 2",
    "Organic Chemistry 1",
    "Organic Chemistry 2",
    "Analytical Chemistry",
    "Physical Chemistry",
    "Inorganic Chemistry",
    "Chemistry Lab",
    "Industrial Chemistry",
    "Polymer Chemistry",
    "Environmental Chemistry",
    "Instrumental Analysis",
    "Medicinal Chemistry",
    "Food Chemistry",
    "Quantum Chemistry",
    "Electrochemistry",
    "Photochemistry",
    "Chemical Safety",
  ],

  "Biology": [
    "General Biology 1",
    "General Biology 2",
    "Microbiology",
    "Genetics",
    "Cell Biology",
    "Molecular Biology",
    "Ecology",
    "Anatomy & Physiology",
    "Biochemistry",
    "Immunology",
    "Biotechnology",
    "Plant Biology",
    "Animal Biology",
    "Developmental Biology",
    "Bioinformatics",
    "Virology",
    "Parasitology",
    "Histology",
    "Evolution",
    "Biostatistics",
    "Marine Biology",
    "Conservation Biology",
    "Entomology",
    "Toxicology",
  ],

  "Business & Management": [
    "Principles of Management",
    "Marketing",
    "Accounting 1",
    "Accounting 2",
    "Financial Management",
    "Microeconomics",
    "Macroeconomics",
    "Business Law",
    "Entrepreneurship",
    "Human Resource Management",
    "Strategic Management",
    "Operations Management",
    "International Business",
    "E-Commerce",
    "Business Ethics",
    "Managerial Accounting",
    "Cost Accounting",
    "Auditing",
    "Taxation",
    "Banking & Finance",
    "Investment Analysis",
    "Supply Chain Management",
    "Organizational Behavior",
    "Principles of Economics",
    "Business Statistics",
    "Management Information Systems",
    "Business Communication",
    "Total Quality Management",
    "Risk Management",
    "Corporate Governance",
    "Islamic Banking",
    "Insurance",
    "Real Estate Management",
    "Retail Management",
    "Digital Marketing",
    "Consumer Behavior",
    "Brand Management",
    "Sales Management",
    "Public Relations",
    "Advertising",
    "Financial Accounting",
    "Intermediate Accounting",
    "Advanced Accounting",
    "Governmental Accounting",
    "International Finance",
    "Portfolio Management",
    "Financial Markets",
    "Money & Banking",
    "Economic Development",
    "Public Finance",
    "Econometrics",
    "Project Feasibility Studies",
    "Leadership",
    "Negotiation Skills",
    "Innovation Management",
  ],

  "Language & Communication": [
    "English 1",
    "English 2",
    "Academic Writing",
    "Technical Writing",
    "Communication Skills",
    "Arabic Language",
    "Public Speaking",
    "Translation",
    "Business English",
    "Scientific English",
    "English Literature",
    "Arabic Literature",
    "Linguistics",
    "Creative Writing",
    "Media Writing",
    "Journalism",
    "French Language",
    "German Language",
    "Spanish Language",
    "English Grammar",
    "Phonetics & Phonology",
    "Semantics",
    "Pragmatics",
    "Sociolinguistics",
    "Applied Linguistics",
    "Second Language Acquisition",
    "Discourse Analysis",
    "Comparative Literature",
    "Literary Criticism",
    "Research Writing",
  ],

  "Islamic Studies & Humanities": [
    "Islamic Culture",
    "Islamic Studies",
    "History of Jordan",
    "Political Science",
    "Sociology",
    "Psychology",
    "Philosophy",
    "Introduction to Law",
    "Human Rights",
    "Ethics",
    "Art History",
    "Quran Sciences",
    "Hadith Sciences",
    "Islamic Jurisprudence",
    "Aqeedah (Islamic Creed)",
    "History of Islamic Civilization",
    "Modern Arab History",
    "World History",
    "International Relations",
    "Public Administration",
    "Constitutional Law",
    "Criminal Law",
    "Civil Law",
    "Commercial Law",
    "Labor Law",
    "Administrative Law",
    "Social Psychology",
    "Developmental Psychology",
    "Abnormal Psychology",
    "Cognitive Psychology",
    "Counseling Psychology",
    "Introduction to Philosophy",
    "Logic",
    "Critical Thinking",
    "Cultural Studies",
    "Gender Studies",
    "Anthropology",
    "Archaeology",
    "Geography",
    "Demography",
    "Media Studies",
    "Political Theory",
    "Comparative Politics",
    "Middle East Studies",
    "National Education",
    "Military Sciences",
  ],

  "Medicine & Health": [
    "Anatomy",
    "Physiology",
    "Pathology",
    "Pharmacology",
    "Clinical Medicine",
    "Public Health",
    "Nursing Fundamentals",
    "Medical Ethics",
    "Epidemiology",
    "Medical Terminology",
    "First Aid",
    "Nutrition",
    "Community Medicine",
    "Internal Medicine",
    "Surgery",
    "Pediatrics",
    "Obstetrics & Gynecology",
    "Psychiatry",
    "Dermatology",
    "Ophthalmology",
    "Orthopedics",
    "Radiology",
    "Anesthesiology",
    "Emergency Medicine",
    "Family Medicine",
    "Medical Genetics",
    "Medical Microbiology",
    "Medical Biochemistry",
    "Histopathology",
    "Clinical Pharmacology",
    "Health Informatics",
    "Hospital Management",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Dental Anatomy",
    "Oral Surgery",
    "Prosthodontics",
    "Orthodontics",
    "Endodontics",
    "Periodontics",
    "Clinical Nutrition",
    "Dietetics",
    "Health Education",
    "Bioethics",
    "Medical Physics",
    "Clinical Laboratory Science",
    "Hematology",
    "Medical Parasitology",
  ],

  "Architecture & Design": [
    "Architectural Design",
    "Building Construction",
    "History of Architecture",
    "Interior Design",
    "Urban Planning",
    "Landscape Architecture",
    "Building Technology",
    "Environmental Design",
    "Graphic Design",
    "3D Modeling",
    "Architectural Drawing",
    "Theory of Architecture",
    "Sustainable Architecture",
    "Building Services",
    "Construction Materials",
    "Site Planning",
    "Housing Design",
    "Commercial Architecture",
    "Restoration & Conservation",
    "Digital Fabrication",
    "Parametric Design",
    "Typography",
    "Visual Communication",
    "Photography",
    "Animation",
    "Product Design",
    "Furniture Design",
    "Color Theory",
    "Design Thinking",
  ],

  "Education": [
    "Educational Psychology",
    "Teaching Methods",
    "Curriculum Design",
    "Educational Technology",
    "Special Education",
    "Classroom Management",
    "Assessment & Evaluation",
    "Educational Research",
    "Foundations of Education",
    "Early Childhood Education",
    "Educational Administration",
    "Inclusive Education",
    "Educational Counseling",
    "Teaching English as a Foreign Language",
    "Mathematics Education",
    "Science Education",
    "Physical Education",
    "Child Development",
    "Learning Theories",
    "Instructional Design",
    "E-Learning",
    "Student Teaching Practicum",
    "School Health",
    "Gifted Education",
  ],

  "Agriculture & Environment": [
    "Plant Science",
    "Soil Science",
    "Animal Science",
    "Agricultural Economics",
    "Horticulture",
    "Crop Production",
    "Plant Protection",
    "Food Science",
    "Food Technology",
    "Dairy Science",
    "Poultry Science",
    "Irrigation & Drainage",
    "Agroforestry",
    "Sustainable Agriculture",
    "Environmental Science",
    "Environmental Impact Assessment",
    "Waste Management",
    "Water Treatment",
    "Air Pollution Control",
    "Climate Change",
    "Natural Resources Management",
  ],

  "Pharmacy": [
    "Pharmaceutical Chemistry",
    "Pharmaceutics",
    "Pharmacognosy",
    "Clinical Pharmacy",
    "Biopharmaceutics",
    "Pharmacy Practice",
    "Toxicology & Forensics",
    "Drug Design",
    "Pharmaceutical Analysis",
    "Pharmaceutical Technology",
    "Pharmacy Law & Ethics",
    "Hospital Pharmacy",
    "Community Pharmacy",
    "Pharmacokinetics",
    "Herbal Medicine",
    "Cosmetics Science",
  ],

  "Media & Journalism": [
    "Mass Communication",
    "Radio & TV Production",
    "Digital Media",
    "Film Studies",
    "Public Opinion",
    "Media Ethics",
    "News Writing & Reporting",
    "Investigative Journalism",
    "Broadcast Journalism",
    "Social Media Management",
    "Media Law",
    "Documentary Filmmaking",
    "Audio Production",
    "Video Editing",
    "Photojournalism",
  ],

  "Fine Arts": [
    "Drawing",
    "Painting",
    "Sculpture",
    "Printmaking",
    "Ceramics",
    "Music Theory",
    "Music Performance",
    "Theater Arts",
    "Dance",
    "Art Criticism",
    "Contemporary Art",
    "Digital Art",
    "Calligraphy",
    "Art Education",
  ],

  "Tourism & Hospitality": [
    "Introduction to Tourism",
    "Hotel Management",
    "Food & Beverage Management",
    "Tourism Marketing",
    "Tour Guiding",
    "Travel Agency Management",
    "Ecotourism",
    "Heritage Tourism",
    "Event Management",
    "Hospitality Law",
    "Front Office Management",
    "Housekeeping Management",
    "Tourism Planning",
    "Airline Management",
    "Tourism Economics",
  ],

  "Library & Information Science": [
    "Information Science",
    "Library Management",
    "Cataloging & Classification",
    "Digital Libraries",
    "Archives Management",
    "Knowledge Management",
    "Research Methods",
    "Academic Librarianship",
  ],
};

/**
 * Flat, deduplicated, alphabetically sorted array of all course names.
 */
export const ALL_COURSES: string[] = Array.from(
  new Set(Object.values(COURSE_CATEGORIES).flat())
).sort((a, b) => a.localeCompare(b));

/**
 * Reverse lookup map for fast category resolution.
 */
const _courseToCategoryMap: Map<string, string> = new Map();
for (const [category, courses] of Object.entries(COURSE_CATEGORIES)) {
  for (const course of courses) {
    // First category wins if a course name appears in multiple categories
    if (!_courseToCategoryMap.has(course)) {
      _courseToCategoryMap.set(course, category);
    }
  }
}

/**
 * Returns which category a course belongs to.
 * Performs a case-insensitive lookup.
 * Returns "Other" if the course is not found in any category.
 */
export function getCategoryForCourse(course: string): string {
  // Try exact match first
  const exact = _courseToCategoryMap.get(course);
  if (exact) return exact;

  // Try case-insensitive match
  const lowerCourse = course.toLowerCase();
  for (const [name, category] of _courseToCategoryMap.entries()) {
    if (name.toLowerCase() === lowerCourse) {
      return category;
    }
  }

  return "Other";
}
